language: node_js
node_js: stable

cache: npm

before_install:
  - npm install -g @tarojs/cli@1.1.9

script:
  - npm run test:ci

after_script:
  - echo 'taro-calendar.aotu.io' > CNAME
  - cd dist
  - git init
  - git config user.name "travis"
  - git config user.email "taro-calendar@travis.com"
  - git add .
  - git commit -m "docs:Update Document"
  - git push -f "https://${GIT_TOKEN}@${GIH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GIH_REF: github.com/NervJS/taro-calendar.git